In [2]:
import numpy as np
import pandas as pd

In [3]:

# Function to generate a random similarity matrix
def generate_similarity_matrix(size):
    # Generate a random matrix with values between 0 and 1
    matrix = np.random.rand(size, size)
    
    # Make the matrix symmetric: M[i,j] = M[j,i]
    matrix = np.triu(matrix, k=1) + np.triu(matrix, k=1).T
    
    # Set diagonal to 1
    np.fill_diagonal(matrix, 1)
    
    return matrix

# Set matrix size
matrix_size = 5

# Generate three similarity matrices of size 10x10
M1_sim = generate_similarity_matrix(matrix_size)
M2_sim = generate_similarity_matrix(matrix_size)
M3_sim = generate_similarity_matrix(matrix_size)

# Assign weights (all set to 1 for no weight modification)
w1, w2, w3 = 1.0, 1.0, 1.0

# Apply noisy-OR formula element-wise to combine the matrices
combined_matrix_sim = 1 - (1 - M1_sim)**w1 * (1 - M2_sim)**w2 * (1 - M3_sim)**w3
combined_matrix_sim

array([[1.        , 0.87105169, 0.77532099, 0.87591425, 0.84481066],
       [0.87105169, 1.        , 0.97782974, 0.70313218, 0.77207261],
       [0.77532099, 0.97782974, 1.        , 0.95114054, 0.95460028],
       [0.87591425, 0.70313218, 0.95114054, 1.        , 0.89780721],
       [0.84481066, 0.77207261, 0.95460028, 0.89780721, 1.        ]])

In [9]:
def optimized_noisy_or_kernel_list(kernels,alpha):
    combined_kernel = kernels[0]
    
    for kernel in kernels[1:]:
        combined_kernel = 1 - (1 - combined_kernel)**alpha * (1 - kernel)**alpha
        
    return combined_kernel
optimized_noisy_or_kernel_list([M1_sim, M2_sim, M3_sim],0.6)

array([[1.        , 0.54189085, 0.42133431, 0.54984975, 0.50151552],
       [0.54189085, 1.        , 0.74806412, 0.42921418, 0.48841515],
       [0.42133431, 0.74806412, 1.        , 0.72305659, 0.81175458],
       [0.54984975, 0.42921418, 0.72305659, 1.        , 0.60942075],
       [0.50151552, 0.48841515, 0.81175458, 0.60942075, 1.        ]])

In [6]:
M1_sim,M2_sim,M3_sim

(array([[1.        , 0.57240801, 0.90643651, 0.63332267, 0.49337052],
        [0.57240801, 1.        , 0.18440018, 0.11455403, 0.44736737],
        [0.90643651, 0.18440018, 1.        , 0.77189046, 0.72767041],
        [0.63332267, 0.11455403, 0.77189046, 1.        , 0.1212257 ],
        [0.49337052, 0.44736737, 0.72767041, 0.1212257 , 1.        ]]),
 array([[1.        , 0.32455674, 0.0841265 , 0.65937919, 0.99143258],
        [0.32455674, 1.        , 0.30557785, 0.2091262 , 0.80846549],
        [0.0841265 , 0.30557785, 1.        , 0.95321231, 0.3041961 ],
        [0.65937919, 0.2091262 , 0.95321231, 1.        , 0.99758616],
        [0.99143258, 0.80846549, 0.3041961 , 0.99758616, 1.        ]]),
 array([[1.        , 0.77461619, 0.07938655, 0.28586931, 0.90978011],
        [0.77461619, 1.        , 0.88561894, 0.85275335, 0.27375638],
        [0.07938655, 0.88561894, 1.        , 0.65049526, 0.01450684],
        [0.28586931, 0.85275335, 0.65049526, 1.        , 0.32647665],
        [0.90978

In [1]:
import numpy as np
from scipy.linalg import logm

# Step 1: Create a symmetric positive definite (SPD) matrix (5x5)
np.random.seed(42)
A_random = np.random.randn(5, 5)
A = A_random @ A_random.T + 5 * np.eye(5)  # Make it symmetric positive definite

# Step 2: Compute the matrix logarithm
L = logm(A)

# Step 3: Define a permutation of indices
perm = [2, 0, 4, 1, 3]  # just an example permutation

# Step 4: Apply permutation to A (i.e., A' = P A P^T)
A_reordered = A[np.ix_(perm, perm)]

# Step 5: Compute logm of the reordered matrix
L_reordered_direct = logm(A_reordered)

# Step 6: Alternatively, reorder the logm of A directly
L_reordered_from_L = L[np.ix_(perm, perm)]

# Step 7: Compare the two results
print("Are both reordered logm matrices close?")
print(np.allclose(L_reordered_direct, L_reordered_from_L))


Are both reordered logm matrices close?
True
