In [4]:
import numpy as np
import pandas as pd
import os
from features import get_feature, read_data

In [5]:
# pseudo_select_function = [1,2]

root = '/itf-fi-ml/shared/users/ziyuzh/svm'
feature = 'ppi'


out_path = os.path.join(root,'results',feature)
if not os.path.exists(out_path):
    os.mkdir(out_path)

feature_df = get_feature(root,feature)

all_df = pd.read_csv(os.path.join(root,'data','disgent_2020','disgenet_string.csv'))

selected_diseases = (
    all_df.groupby('disease_id')
    .filter(lambda x: len(x) > 20)
    ['disease_id']
    .unique()
    .tolist()
)

In [44]:
disease = 'ICD10_G91'
# disease = selected_diseases[0]

In [25]:
df, X, y = read_data(disease, all_df, feature_df)

In [45]:
all_df[all_df['disease_id']==disease]

disease_id omim             hpo  disease_name  gene_id  score  \
5557  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    L1CAM   0.90   
5558  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    HYDIN   0.75   
5559  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly  CCDC88C   0.75   
5560  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly     MPDZ   0.70   
5561  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    CCND2   0.65   
5562  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    FGFR2   0.65   
5563  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly   TRIM71   0.65   
5564  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly  SMARCC1   0.60   
5565  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly  POMGNT1   0.55   
5566  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly     FZD3   0.55   
5567  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    IFT56   0.55   
5568  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    WDR81   0.55   
5569  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly      TXN   0.55   
5570  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    KIF4A   0.50   
5571  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    PLOD1   0.50   
5572  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    CRPPA   0.45   
5573  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly     DPH1   0.45   
5574  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    DNAH9   0.45   
5575  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly   IFT122   0.40   
5576  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly   TMEM92   0.40   
5577  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly  ARFGEF2   0.40   
5578  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly     NID1   0.40   
5579  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    SIN3A   0.40   
5580  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly   PDGFRB   0.40   
5581  ICD10_G91  NaN  HPO_HP:0000238  Hydrocephaly    KCNT1   0.40   

      first_pub_year  last_pub_year     ei    dsi    dpi uniprot_id  \
5557             NaN            NaN  0.953  0.436  0.913     P32004   
5558          2003.0         2008.0  1.000  0.577  0.739     Q4G0P3   
5559             NaN            NaN  1.000  0.614  0.652     Q9P219   
5560             NaN            NaN  1.000  0.603  0.609     O75970   
5561          2018.0         2018.0  1.000  0.444  0.913     P30279   
5562             NaN            NaN  0.500  0.341  0.913     P21802   
5563             NaN            NaN  1.000  0.667  0.565     Q2Q1W2   
5564             NaN            NaN  1.000  0.598  0.783     Q92922   
5565             NaN            NaN  1.000  0.523  0.696     Q8WZA1   
5566             NaN            NaN  1.000  0.608  0.609     Q9NPG1   
5567             NaN            NaN  1.000  0.579  0.783     A0AVF1   
5568             NaN            NaN  1.000  0.600  0.565     Q562E7   
5569          2019.0         2019.0  1.000  0.424  0.913     P10599   
5570             NaN            NaN  1.000  0.560  0.826     O95239   
5571             NaN            NaN  1.000  0.538  0.783     Q02809   
5572          2012.0         2012.0  1.000  0.551  0.783     A4D126   
5573          2015.0         2015.0  1.000  0.589  0.826     Q9BZG8   
5574             NaN            NaN  0.000  0.583  0.696     Q9NYC9   
5575          2010.0         2010.0  1.000  0.564  0.783     Q9HBG6   
5576          2015.0         2015.0  1.000  0.804  0.348     Q6UXU6   
5577          2015.0         2015.0  1.000  0.624  0.609     Q9Y6D5   
5578          2015.0         2015.0  1.000  0.575  0.870     P14543   
5579          2016.0         2016.0  1.000  0.520  0.870     Q96ST3   
5580             NaN            NaN  0.000  0.384  0.913     P09619   
5581             NaN            NaN  0.000  0.539  0.609     Q5JUK3   

                 string_id  
5557  9606.ENSP00000359077  
5558  9606.ENSP00000377197  
5559  9606.ENSP00000374507  
5560  9606.ENSP00000320006  
5561  9606.ENSP00000261254  
5562  9606.ENSP00000410294  
5563  9606.ENSP00000373272  
5564  9606.ENSP00000254480  
5565  9606.ENSP00000361060  
5566  9606.ENSP00000240093  
5567  9606.ENSP000

In [28]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import KFold, GridSearchCV
from rdkit.ML.Scoring.Scoring import CalcBEDROC
# from pseudo_label import select_pseudo_negatives

from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score

In [29]:

kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Get the positive class samples
X_pos = X[y == 1]
y_pos = y[y == 1]

fold = 0
train_idx, test_idx = next(kf.split(X_pos))

X_train_pos, X_test_pos = X_pos[train_idx], X_pos[test_idx]
y_train_pos, y_test_pos = y_pos[train_idx], y_pos[test_idx]
neg_num = X_train_pos.shape[0]


In [30]:
train_pos = df[df['label']==1].iloc[train_idx]['string_id'].tolist()
test_pos = df[df['label']==1].iloc[test_idx]['string_id'].tolist()

In [31]:
local_stringdb = os.path.join('/itf-fi-ml/shared/users/ziyuzh/svm/data/stringdb','2023')

ppidf = pd.read_csv(os.path.join(local_stringdb,'9606.protein.info.v12.0.txt'), sep='\t', header=0, usecols=['#string_protein_id', 'preferred_name'])
ppidf['preferred_name'] = ppidf['preferred_name'].str.upper()
stringId2name = ppidf.set_index('#string_protein_id')['preferred_name'].to_dict()
name2stringId = ppidf.set_index('preferred_name')['#string_protein_id'].to_dict()
ppidf = pd.read_csv(os.path.join(local_stringdb,'9606.protein.aliases.v12.0.txt'), sep='\t', header=0, usecols=['#string_protein_id', 'alias']).drop_duplicates(['alias'], keep='first')
ppidf['alias'] = ppidf['alias'].str.upper()
aliases2stringId = ppidf.set_index('alias')['#string_protein_id'].to_dict()

In [32]:
for g in train_pos:
    print(stringId2name[g])

VPS16
ACTB
VPS11
SPR
ALDH5A1
CIZ1
NUP54
CYP2D6
GNAL
TH
EIF2AK2
TOR1A
ATP1A3
SLC30A10
SCP2
TIMM8A
CHRNA4
KCNN2
TMEM151A
COL6A3
KMT2B
GLRA1
ANO3
AOPEP


In [33]:
for g in test_pos:
    print(stringId2name[g])

PRKRA
TSPOAP1
GCH1
SHQ1
THAP1
SERAC1


In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier 

# Define the custom scoring function
def custom_score(y_true, y_proba):
    scores = np.column_stack((y_true, y_proba))  
    scores = scores[scores[:, 1].argsort()[::-1]] 
    return CalcBEDROC(scores, col=0, alpha=160.9)  

# Wrap the custom_score function using make_scorer
custom_scorer = make_scorer(custom_score, response_method='predict_proba')

def select_parameter_svm(X_train, y_train, metric):
    # Define parameter grid
    param_grid = {
        'C': [0.1, 0.5, 0.8, 1, 10],
        'kernel': ['rbf'],
        'gamma': ['scale', 'auto', 0.1, 1, 10, 100]
    }
    
    # Initialize SVM with probability estimates
    clf = svm.SVC(probability=True)
    
    if metric == 'bedroc_1':
        grid_search = GridSearchCV(clf, param_grid, cv=5, scoring=custom_scorer, verbose=1)
    elif metric == 'auroc':
        grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='roc_auc', verbose=1)
    grid_search.fit(X_train, y_train)
    print('svm')
    return grid_search.best_params_

def select_parameter_rf(X_train, y_train, metric):
    # Define parameter grid for RandomForestClassifier
    param_grid = {
    'n_estimators' : [ 10, 20, 50, 100], 
    'max_features' : [ 20,50,100]
} 

    # Initialize RandomForestClassifier
    clf = RandomForestClassifier()

    # Perform GridSearchCV based on the metric
    if metric == 'bedroc_1':
        grid_search = GridSearchCV(clf, param_grid, cv=5, scoring=custom_scorer, verbose=1)
    elif metric == 'auroc':
        grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='roc_auc', verbose=1)

    # Fit the grid search
    grid_search.fit(X_train, y_train)
    print('rf')
    
    return grid_search.best_params_

def select_parameter_mlp(X_train, y_train, metric):
    # Define parameter grid for RandomForestClassifier
    param_grid = {
            "alpha": [1, 0.5,0.1, 0.01],
              "hidden_layer_sizes": [(100,100),
                                     (100,100,100),
                                     (128,128),
                                     (128,128,128)],
              "activation": ["relu"]}

    # Initialize RandomForestClassifier
    clf = MLPClassifier(max_iter=500, early_stopping=True)

    # Perform GridSearchCV based on the metric
    if metric == 'bedroc_1':
        grid_search = GridSearchCV(clf, param_grid, cv=5, scoring=custom_scorer, verbose=1)
    elif metric == 'auroc':
        grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='roc_auc', verbose=1)

    # Fit the grid search
    grid_search.fit(X_train, y_train)
    
    print('mlp')
    
    return grid_search.best_params_

def calculate_ranks(values):
    return np.argsort(np.argsort(values)) + 1


In [34]:
from model import eval,eval_assemble
from rdkit.ML.Scoring.Scoring import CalcBEDROC

In [36]:
results = []
selected_neg_indices = np.random.choice(np.where(y == 0)[0], size=neg_num, replace=False)
X_train_neg = X[selected_neg_indices]
y_train_neg = y[selected_neg_indices]
X_train = np.vstack((X_train_pos, X_train_neg))
y_train = np.hstack((y_train_pos, y_train_neg))
# Get the remaining samples by masking the selected indices
remaining_neg_indices = np.setdiff1d(np.where(y == 0)[0], selected_neg_indices)
X_test_neg = X[remaining_neg_indices]
y_test_neg = y[remaining_neg_indices]
X_test = np.vstack((X_test_pos, X_test_neg))
y_test = np.hstack((y_test_pos, y_test_neg))

parameters = select_parameter_svm(X_train, y_train,'auroc')
best_svm = svm.SVC(**parameters)
best_svm.fit(X_train, y_train)
y_score = best_svm.decision_function(X_test)
    
results.append(eval(best_svm, X_train, y_train, X_test, y_test))
print(results)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
svm
[(0.16666666666666666, 0.000510986203372509, 0.0030659172202350538, 0.5, 0.0005108991825613079, 0.0010217983651226157, 0.6920737939493049, 0.308, 0.00010164268931909948, 0.03993164569338889, 0.10430412612238822, 0.30865825150283366)]


In [37]:
y_score[:10]

array([ 0.03337485, -0.00844697,  0.07678321, -0.03931246,  0.0203466 ,
       -0.02604483,  0.03133975, -0.00974343, -0.03397912,  0.0490527 ])

In [53]:
y_score[np.argsort(y_score)[-10:][::-1]]

array([1.30889118, 1.21866616, 1.15505981, 1.15356624, 1.1449833 ,
       1.09607861, 1.03860858, 1.01824334, 0.98304358, 0.95736904])

In [33]:
remaining_neg_indices[np.argsort(y_score)[-10:][::-1]]

array([5799, 4818, 2238, 5427, 2142, 6204, 6131, 1981,    1, 5593])

In [36]:
arr = X[y==0][remaining_neg_indices[np.argsort(y_score)[-10:][::-1]]]

In [50]:
df.iloc[df[df['label']==0].index[remaining_neg_indices[np.argsort(y_score)[-10:][::-1]]]]['string_id'].map(stringId2name)

5813       OCA2
4826      RTN4R
2241      CRPPA
5439     GUCY2C
2145      RPL36
6219     ATP2A1
6146        IL9
1983       CDK1
1       RALGPS2
5606      CLCN2
Name: string_id, dtype: object

In [36]:
train_neg = df.iloc[selected_neg_indices]['string_id'].tolist()
test_neg = df.iloc[remaining_neg_indices]['string_id'].tolist()

In [85]:
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import fcluster, linkage

def calculate_proportion(hierarchical_labels, y_train, func):
    proportion = []
    unique_clusters = np.unique(hierarchical_labels)
    
    # Total number of samples with label 1
    total_y1 = np.sum(y_train == 1)
    if total_y1 == 0:
        raise ValueError("No positive samples in training data")

    for c in unique_clusters:
        cluster_indices = np.where(hierarchical_labels == c)[0]
        cluster_y1 = np.sum(y_train[cluster_indices] == 1)
        
        if func == 1:
            A_i = len(cluster_indices) * (1 - (cluster_y1 / total_y1))
        elif func == 2:
            A_i = max(0, 2 * len(cluster_indices) / len(y_train) - (cluster_y1 / total_y1))
        elif func == 3:
            A_i = max(0, 2 * len(cluster_indices) / len(y_train) - (cluster_y1 / total_y1))
            if cluster_y1 == 0:
                # A_i = np.exp(0.05 * A_i)
                A_i = A_i**0.5
        
        proportion.append(A_i)
        ###################
        print(c, len(cluster_indices), cluster_y1, total_y1)
        ###################
    return proportion

def cluster_negative_sampling(hierarchical_labels, y_train, proportion, neg_size):
    neg_cluster = []
    all_sampled_negatives = []
    unique_clusters = np.unique(hierarchical_labels)
    total_proportion = sum(proportion)

    if total_proportion == 0:
        raise ValueError("Sum of proportions is zero. Check the 'proportion' calculation.")

    for index, c in enumerate(unique_clusters):
        A_i = proportion[index]
        neg_i = int((A_i / total_proportion) * neg_size)

        cluster_indices = np.where(hierarchical_labels == c)[0]
        negative_indices = cluster_indices[y_train[cluster_indices] == 0]

        if len(negative_indices) == 0:
            continue  
        neg_i = min(neg_i, len(negative_indices))  # Adjust to max available

        ################################
        print(c, neg_i)
        ################################

        sampled_indices = np.random.choice(negative_indices, size=neg_i, replace=False)
        all_sampled_negatives.extend(sampled_indices)
        neg_cluster.append(neg_i)

    return all_sampled_negatives

def select_pseudo_negatives(neg_num, X_train_pos, y_train_pos, X_all_neg, y_all_neg, func):
    # Combine positive and negative samples
    X_train = np.vstack((X_train_pos, X_all_neg))
    y_train = np.hstack((y_train_pos, y_all_neg))

    # Hierarchical clustering
    model = AgglomerativeClustering(distance_threshold=0, n_clusters=None, compute_distances=True)
    model.fit(X_train)

    # Get linkage matrix
    mat = linkage(X_train, method='ward')

    # Get first-level labels
    n_clusters = 5
    hierarchical_labels = fcluster(mat, n_clusters, criterion='maxclust')
    #####################################
    print('label ready')
    #####################################

    # Sample negatives
    proportion = calculate_proportion(hierarchical_labels, y_train, func)
    all_sampled_negatives = cluster_negative_sampling(hierarchical_labels, y_train, proportion, neg_num)

    return hierarchical_labels, all_sampled_negatives, X_train[all_sampled_negatives], y_train[all_sampled_negatives]

In [166]:
hierarchical_labels, all_sampled_negatives, X_train_neg2, y_train_neg2 = select_pseudo_negatives(neg_num, X_train_pos, y_train_pos, X[y==0], y[y==0],3)
# dtype = X.dtype.descr  # Get data type of elements
# X_y0_view = X[y == 0].view(dtype=[('', X.dtype)] * X.shape[1])
# X_train_neg_view = X_train_neg2.view(dtype=[('', X.dtype)] * X.shape[1])
# X_test_neg2 = np.setdiff1d(X_y0_view, X_train_neg_view).view(X.dtype).reshape(-1, X.shape[1])  

select_index = all_sampled_negatives - np.sum(np.hstack((y_train_pos, y[y==0])) == 1) +1
X_all_neg_add0 = np.vstack((np.zeros((1, X.shape[1])), X[y==0]))
select_index_add0 = np.hstack((np.zeros((1,)), select_index))
test_neg_index = np.setdiff1d(np.arange(X_all_neg_add0.shape[0]),select_index_add0)
X_test_neg2 = X_all_neg_add0[test_neg_index]

X_train2 = np.vstack((X_train_pos, X_train_neg2))
y_train2 = np.hstack((y_train_pos, y_train_neg2))

X_test2 = np.vstack((X_test_pos, X_test_neg2))
y_test2 = np.array([1]*X_test_pos.shape[0]+[0]*X_test_neg2.shape[0])


label ready
1 808 0 14
2 2153 6 14
3 6012 2 14
4 382 0 14
5 9488 6 14
1 2
2 0
3 4
4 1
5 5


In [ ]:
from model import select_parameter, eval
parameters = select_parameter(X_train, y_train)
best_svm = svm.SVC(**parameters)
eval(best_svm, X_train, y_train, X_test, y_test)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


(1.0,
 0.0010655301012253596,
 1.0,
 0.002126528442317916,
 0.002126528442317916,
 1.0,
 0.00070859167404783,
 0.00070859167404783,
 0.9557533882540526,
 0.0444,
 0.37922130994475545,
 0.5050062156974067,
 0.6115934075984235,
 0.8106669636266506)

In [169]:
X_test.shape, X_test2.shape

((18819, 1024), (18821, 1024))

In [ ]:
parameters = select_parameter(X_train2, y_train2)
best_svm = svm.SVC(**parameters)
eval(best_svm, X_train2, y_train2, X_test2, y_test2)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


(1.0,
 0.0002125285585250518,
 0.25,
 0.0005313496280552603,
 0.0021253985122210413,
 0.5,
 0.00035423308537017357,
 0.0007084661707403471,
 0.7225647021310516,
 0.2775,
 0.0010832886657002932,
 0.08734681288406333,
 0.1736007952801108,
 0.36923901651443924)

In [87]:
total_y1 = 14

In [88]:
fracs1 = calculate_proportion(hierarchical_labels, np.hstack((y_train_pos, y[y==0])), 1)
cluster_negative_sampling(hierarchical_labels, np.hstack((y_train_pos, y[y==0])), fracs1, total_y1)

1 808 0 14
2 2153 6 14
3 6012 2 14
4 382 0 14
5 9488 6 14
1 0
2 1
3 5
4 0
5 5


[18498, 224, 12645, 17749, 3059, 13154, 6139, 108, 12974, 4511, 10541]

In [89]:
fracs2 = calculate_proportion(hierarchical_labels, np.hstack((y_train_pos, y[y==0])), 2)
cluster_negative_sampling(hierarchical_labels, np.hstack((y_train_pos, y[y==0])), fracs2, total_y1)

1 808 0 14
2 2153 6 14
3 6012 2 14
4 382 0 14
5 9488 6 14
1 1
2 0
3 5
4 0
5 6


[162, 9694, 13885, 13716, 17386, 7857, 559, 7796, 2185, 208, 3611, 9906]

In [90]:
fracs3 = calculate_proportion(hierarchical_labels, np.hstack((y_train_pos, y[y==0])), 3)
cluster_negative_sampling(hierarchical_labels, np.hstack((y_train_pos, y[y==0])), fracs3, total_y1)

1 808 0 14
2 2153 6 14
3 6012 2 14
4 382 0 14
5 9488 6 14
1 2
2 0
3 4
4 1
5 5


[615, 10421, 11942, 18110, 16625, 6087, 6521, 16290, 9091, 7701, 10926, 13555]

In [96]:
np.where(y[y==0]==0), np.where(np.hstack((y_train_pos, y[y==0]))==0)

((array([    0,     1,     2, ..., 18826, 18827, 18828]),),
 (array([   14,    15,    16, ..., 18840, 18841, 18842]),))

In [102]:
X[y==0][615],np.vstack((X_train_pos, X[y==0]))[615+np.sum(np.hstack((y_train_pos, y[y==0])) == 1)]

(array([ 0.02728 ,  0.0634  ,  0.03085 , ...,  0.01265 , -0.0102  ,
         0.005836]),
 array([ 0.02728 ,  0.0634  ,  0.03085 , ...,  0.01265 , -0.0102  ,
         0.005836]))

In [ ]:

select_index

array([10018,  7149, 14247, 14200,  6616,  9397,  9957, 16276,  3334,
       15167, 13425])

In [147]:
all_sampled_negatives

[10031, 7162, 14260, 14213, 6629, 9410, 9970, 16289, 3347, 15180, 13438]

In [148]:
np.vstack((X_train_pos, X[y==0]))[all_sampled_negatives]

array([[ 0.01498  , -0.00929  ,  0.0608   , ..., -0.06152  ,  0.02278  ,
         0.04175  ],
       [ 0.01881  , -0.0004587,  0.04816  , ...,  0.0819   ,  0.1083   ,
        -0.02129  ],
       [ 0.07     ,  0.0387   ,  0.0387   , ...,  0.000979 , -0.0552   ,
         0.0126   ],
       ...,
       [-0.00756  , -0.04572  ,  0.0443   , ...,  0.002937 ,  0.0604   ,
         0.05484  ],
       [ 0.04584  ,  0.06805  ,  0.033    , ...,  0.0314   , -0.01584  ,
         0.01378  ],
       [ 0.03098  ,  0.1173   ,  0.03056  , ...,  0.001677 ,  0.02406  ,
         0.05276  ]])

In [149]:
np.vstack((np.zeros((1, X.shape[1])), X[y==0]))[select_index]

array([[ 0.01498  , -0.00929  ,  0.0608   , ..., -0.06152  ,  0.02278  ,
         0.04175  ],
       [ 0.01881  , -0.0004587,  0.04816  , ...,  0.0819   ,  0.1083   ,
        -0.02129  ],
       [ 0.07     ,  0.0387   ,  0.0387   , ...,  0.000979 , -0.0552   ,
         0.0126   ],
       ...,
       [-0.00756  , -0.04572  ,  0.0443   , ...,  0.002937 ,  0.0604   ,
         0.05484  ],
       [ 0.04584  ,  0.06805  ,  0.033    , ...,  0.0314   , -0.01584  ,
         0.01378  ],
       [ 0.03098  ,  0.1173   ,  0.03056  , ...,  0.001677 ,  0.02406  ,
         0.05276  ]])

In [153]:
test_1_neg.shape, X[y==0].shape, len(all_sampled_negatives)

((18818, 1024), (18829, 1024), 11)

In [154]:
X_train_neg2 = np.vstack((X_train_pos, X[y==0]))[all_sampled_negatives]
dtype = X.dtype.descr  # Get data type of elements
X_y0_view = X[y == 0].view(dtype=[('', X.dtype)] * X.shape[1])
X_train_neg_view = X_train_neg2.view(dtype=[('', X.dtype)] * X.shape[1])
X_test_neg2 = np.setdiff1d(X_y0_view, X_train_neg_view).view(X.dtype).reshape(-1, X.shape[1]) 

In [ ]:
np.array_equal(X_test_neg2,test_1_neg)

False

In [158]:
X_test_neg2

array([[-0.1626 ,  0.0713 ,  0.07477, ...,  0.01704,  0.1587 , -0.0572 ],
       [-0.1482 ,  0.1383 ,  0.1103 , ...,  0.09534,  0.0857 ,  0.0679 ],
       [-0.139  ,  0.1844 ,  0.1327 , ...,  0.04663,  0.0678 ,  0.07007],
       ...,
       [ 0.1997 ,  0.0871 ,  0.0445 , ..., -0.1324 ,  0.1738 ,  0.06573],
       [ 0.2004 ,  0.1542 , -0.01544, ..., -0.05084,  0.04562, -0.01779],
       [ 0.2065 ,  0.1438 , -0.0892 , ..., -0.1326 ,  0.03998,  0.1515 ]])

In [159]:
test_1_neg

array([[ 0.0368  , -0.01436 ,  0.04453 , ...,  0.0305  ,  0.05273 ,
         0.02362 ],
       [ 0.06207 , -0.03644 ,  0.01286 , ..., -0.0389  ,  0.03513 ,
         0.0466  ],
       [-0.000283,  0.0954  ,  0.02435 , ..., -0.02948 ,  0.007755,
         0.04434 ],
       ...,
       [ 0.0417  ,  0.03415 ,  0.0168  , ..., -0.00958 , -0.001243,
         0.013115],
       [ 0.0922  , -0.004875,  0.06155 , ...,  0.02069 ,  0.11115 ,
         0.1022  ],
       [ 0.014244,  0.0847  ,  0.02559 , ..., -0.0188  , -0.01155 ,
         0.03864 ]])

In [162]:
df_neg_2 = pd.DataFrame(X_test_neg2)
df_neg_1 = pd.DataFrame(test_1_neg)

In [164]:
df_neg_2.shape,df_neg_1.shape

((18818, 1024), (18818, 1024))

In [165]:
pd.merge(df_neg_2, df_neg_1, how='inner')

0        1         2        3        4        5        6        7     \
0     -0.1626  0.07130  0.074770  0.04400  0.06305 -0.11920 -0.01753 -0.21560   
1     -0.1482  0.13830  0.110300 -0.05585 -0.03845 -0.08780 -0.12463 -0.14880   
2     -0.1390  0.18440  0.132700 -0.02540 -0.02960 -0.11560 -0.03604 -0.07170   
3     -0.1368 -0.00502  0.029050 -0.01820 -0.01316  0.02803 -0.02254 -0.07684   
4     -0.1359 -0.02455  0.037930  0.02295  0.02830 -0.01974 -0.04654 -0.04580   
...       ...      ...       ...      ...      ...      ...      ...      ...   
18813  0.1890  0.11530  0.014465  0.11250  0.11580 -0.07040  0.21980 -0.33940   
18814  0.1891  0.01279  0.073800  0.04733  0.01533 -0.06790  0.18650 -0.20340   
18815  0.1997  0.08710  0.044500  0.02210  0.22030  0.10870 -0.18150  0.01538   
18816  0.2004  0.15420 -0.015440  0.10240  0.11646  0.07100  0.17850 -0.23690   
18817  0.2065  0.14380 -0.089200  0.08760  0.10020 -0.00291 -0.06305 -0.11255   

           8         9     ...     1014      1015      1016     1017  \
0     -0.001537 -0.104550  ...  0.00231 -0.029900 -0.103000 -0.11990   
1     -0.058930 -0.223500  ...  0.07120 -0.102540 -0.014404 -0.10820   
2     -0.021410 -0.135300  ... -0.00941 -0.078250 -0.097800 -0.04715   
3      0.006454  0.011420  ... -0.01804 -0.011930 -0.010110 -0.03723   
4      0.007156 -0.007412  ...  0.02070  0.000252  0.000373 -0.09330   
...         ...       ...  ...      ...       ...       ...      ...   
18813 -0.098140  0.281000  ... -0.06793  0.100300 -0.045440 -0.23030   
18814 -0.101200  0.263400  ... -0.09530  0.027760 -0.058100 -0.13180   
18815  0.010420  0.077400  ...  0.08264  0.005140 -0.014854 -0.12560   
18816 -0.032650  0.173300  ... -0.14100  0.040000 -0.098000 -0.16040   
18817 -0.112550 -0.063230  ...  0.00149 -0.062900 -0.153000 -0.10240   

           1018     1019      1020      1021     1022     1023  
0      0.108500  0.14040 -0.002398  0.017040  0.15870 -0.05720  
1      0.037300 -0.10455  0.060460  0.095340  0.08570  0.06790  
2      0.181000 -0.08530 -0.077400  0.046630  0.06780  0.07007  
3      0.015100  0.02060  0.012180 -0.017030  0.05927  0.08514  
4      0.087500  0.04376  0.044860 -0.008940  0.11755  0.10260  
...         ...      ...       ...       ...      ...      ...  
18813  0.140400 -0.20580 -0.207900  0.010574  0.04565  0.11620  
18814  0.120900 -0.13160 -0.139200  0.027440  0.10940  0.06690  
18815  0.012570 -0.12290  0.034450 -0.132400  0.17380  0.06573  
18816  0.039580 -0.09310 -0.148800 -0.050840  0.04562 -0.01779  
18817  0.011406 -0.15950 -0.006570 -0.132600  0.03998  0.15150  

[18818 rows x 1024 columns]