In [1]:
import numpy as np
from multiprocessing import Pool
import pickle

In [1]:
import os
import glob
import pickle

In [8]:
feature_names = 'uniport_ppi_2017-uniport_exp-uniport_seq'
early_dir = '/itf-fi-ml/shared/users/ziyuzh/svm/results/early_concat'
early_files = glob.glob(os.path.join(early_dir, f'{feature_names}*.pkl'))
if early_files:
    K_path = dict()
    for file in early_files:
        ratio = int(file.split('/')[-1].split('_')[-2])
        K_path[ratio] = [file]

In [9]:
K_path

{8: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/early_concat/uniport_ppi_2017-uniport_exp-uniport_seq_K_8_0.43594641319632244.pkl'],
 4: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/early_concat/uniport_ppi_2017-uniport_exp-uniport_seq_K_4_0.8718928263926449.pkl'],
 2: ['/itf-fi-ml/shared/users/ziyuzh/svm/results/early_concat/uniport_ppi_2017-uniport_exp-uniport_seq_K_2_1.7437856527852897.pkl']}

In [5]:
# Load the data from the file
with open('/itf-fi-ml/shared/users/ziyuzh/svm/results/uni_kernel_cv_scaled/2019/path_save.pkl', 'rb') as f:
    item = pickle.load(f)
print(item.keys())
# Remove keys that start with 'ppi' and their corresponding values
item = {key: value for key, value in item.items() if not key.startswith('ppi')}
print(item.keys())
# Save the updated dictionary back to the file
with open('/itf-fi-ml/shared/users/ziyuzh/svm/results/uni_kernel_cv_scaled/2019/path_save.pkl', 'wb') as f:
    pickle.dump(item, f)

dict_keys(['uniport_ppi_2019', 'uniport_bio', 'uniport_seq', 'uniport_esm', 'ppi_2019_dw_80', 'ppi_2019_dw_10', 'ppi_2019_dw_40'])
dict_keys(['uniport_ppi_2019', 'uniport_bio', 'uniport_seq', 'uniport_esm'])


In [17]:
epsilon = 1e-12
for key in ['linear_fused', 'geo_fused']:
    K = item[key][0]
    diag = np.sqrt(np.diag(K))
    denom = diag[:, None] * diag[None, :] + epsilon
    K_normalized = K / denom
    K_normalized = 0.5 * (K_normalized + K_normalized.T)  # Enforce symmetry
    item[key][0] = K_normalized


In [18]:

with open('/itf-fi-ml/shared/users/ziyuzh/svm/results/kerlens/2019_update.pkl', 'wb') as f:
    pickle.dump(item, f)

In [9]:
with open('/itf-fi-ml/shared/users/ziyuzh/svm/results/kerlens/2017.pkl', 'rb') as f:
    item2 = pickle.load(f)

In [10]:
item['geo_fused'][0].shape, item2['geo_fused'][0].shape

((12925, 12925), (12925, 12925))

In [11]:

np.array_equal(item['geo_fused'][0], item2['geo_fused'][0])


False

In [ ]:
updated_dict = dict()
ks = []
logks = []
for feature_name in list(item.keys())[:4]:
    K = item[feature_name][0]
    ks.append(K)
    eigenvalues, eigenvectors = np.linalg.eigh(K)
    eigenvalues = np.clip(eigenvalues, 1e-12, None)
    K_log = eigenvectors @ np.diag(np.log(eigenvalues)) @ eigenvectors.T
    logks.append(K_log)
    updated_dict[feature_name] = [K,K_log]
    

updated_dict['linear_fused'] = [np.mean(ks, axis=0)]

logk_avg = np.mean(logks, axis=0)

eigenvalues, eigenvectors = np.linalg.eigh(logk_avg)
eigenvalues = np.clip(eigenvalues, -50, 50)
K_geo_mean = eigenvectors @ np.diag(np.exp(eigenvalues)) @ eigenvectors.T
K_geo_mean = 0.5 * (K_geo_mean + K_geo_mean.T)  # enforce symmetry
updated_dict['geo_fused'] = [K_geo_mean]

dict_keys(['ppi_2019', 'bioconcept', 'uniport', 'esm2', 'linear_fused', 'geo_fused'])

In [ ]:
import numpy as np
from sklearn.metrics.pairwise import rbf_kernel
from scipy.linalg import logm, expm


# Step 1: Create dataset (100 samples, 3 features)
X = np.random.rand(20, 3)
Z = np.random.rand(20, 3)
Y = np.random.rand(20, 3)


gamma = 1.0 / X.shape[1]
K1 = rbf_kernel(X, X, gamma=gamma)
K2 = rbf_kernel(Y, Y, gamma=gamma)
K3 = rbf_kernel(Z, Z, gamma=gamma)
Ks = [K1,K2,K3]

Ks = [K1, K2, K3]  # list of SPD kernel matrices
logks = []

for K in Ks:
    eigenvalues, eigenvectors = np.linalg.eigh(K)
    eigenvalues = np.clip(eigenvalues, 1e-12, None)
    K_log = eigenvectors @ np.diag(np.log(eigenvalues)) @ eigenvectors.T
    logks.append(K_log)

logk_avg = np.mean(logks, axis=0)

eigenvalues, eigenvectors = np.linalg.eigh(logk_avg)
eigenvalues = np.clip(eigenvalues, -50, 50)
K_geo_mean = eigenvectors @ np.diag(np.exp(eigenvalues)) @ eigenvectors.T
K_geo_mean = 0.5 * (K_geo_mean + K_geo_mean.T)  # enforce symmetry


In [26]:
K_geo_mean

array([[0.88455566, 0.82891577, 0.87371259, 0.86299127, 0.86441367,
        0.85305208, 0.85173915, 0.86775089, 0.85996461, 0.84063537,
        0.85798507, 0.8652169 , 0.8654578 , 0.8346137 , 0.86765266,
        0.88759061, 0.87050142, 0.83894802, 0.85889171, 0.87317854],
       [0.82891577, 0.80247038, 0.8117951 , 0.81108814, 0.80827939,
        0.79447393, 0.79669527, 0.81474665, 0.7998256 , 0.78424389,
        0.80364889, 0.80798626, 0.80344428, 0.78007251, 0.81043369,
        0.82610872, 0.8171241 , 0.79040552, 0.80104584, 0.81833883],
       [0.87371259, 0.8117951 , 0.88236211, 0.86332046, 0.86452415,
        0.85150861, 0.84380449, 0.85992071, 0.85907228, 0.82900081,
        0.85516017, 0.86246843, 0.87198581, 0.83501148, 0.86199215,
        0.8827739 , 0.8741223 , 0.83443879, 0.84925554, 0.87295162],
       [0.86299127, 0.81108814, 0.86332046, 0.86225669, 0.84984034,
        0.84105297, 0.82972822, 0.85179253, 0.84857065, 0.81893658,
        0.84437567, 0.85290584, 0.854589  , 0

In [14]:
K_log

array([ -6.48848682,  -1.91616441,  -3.46257234,  -0.95230106,
        -1.51826265,   7.65110352,  -3.73934789,  -6.88148643,
        -9.16641917,  -1.86479741,   3.35084753,  -0.6552726 ,
        12.36966556,  -5.99989032, -19.30849231,  -6.07467455,
         5.59405539,   1.63442807,  -1.79286882,   1.53577359])

In [4]:
def is_spd(A, tol=1e-8):
    # Check symmetry
    if not np.allclose(A, A.T, atol=tol):
        return False
    # Check eigenvalues > 0
    eigvals = np.linalg.eigvalsh(A)
    return np.all(eigvals > tol)

def project_to_spd(A, tol=1e-8):
    # Make symmetric
    A = (A + A.T) / 2
    eigvals, eigvecs = eigh(A)
    eigvals_clipped = np.clip(eigvals, tol, None)  # set eigenvalues < tol to tol
    return eigvecs @ np.diag(eigvals_clipped) @ eigvecs.T

def make_psd(K, min_eig=1e-6):
    K = (K + K.T) / 2
    eigvals = np.linalg.eigvalsh(K)
    if np.min(eigvals) < min_eig:
        K += np.eye(K.shape[0]) * (min_eig - np.min(eigvals))
    return K

def process_kernel(args):
    K, w = args
    K = make_psd(K)
    log_K = logm(K)
    if np.iscomplexobj(log_K) and np.allclose(log_K.imag, 0, atol=1e-10):
        log_K = log_K.real
    return w * log_K

def weighted_log_euclidean_mean(kernels, weights):
    weights = np.array(weights)
    weights = weights / weights.sum()

    with Pool(processes=len(weights)) as pool:
        weighted_logs = pool.map(process_kernel, zip(kernels, weights))

    log_sum = np.sum(weighted_logs, axis=0)
    return expm(log_sum)

In [3]:
import pandas as pd

In [4]:
import numpy as np
from sklearn.metrics.pairwise import rbf_kernel

# Step 1: Simulate data with 10 samples and 4 features
np.random.seed(0)
X = np.random.rand(10, 4)

# Step 2: Define feature weights
feature_weights = [0.1, 0.3, 0.4, 0.2]

# Step 3: Define RBF gamma (can be adjusted or auto)
gamma = 1.0  # or use 1 / (2 * sigma^2)

# Step 4: Compute RBF kernels for each feature individually
kernels_all = [rbf_kernel(X[:, i:i+1], gamma=gamma) for i in range(4)]

# Step 5: Compute weighted sum of kernel matrices
K_weight_rbf_all = sum(w * K for w, K in zip(feature_weights, kernels_all))



In [5]:
K_weight_rbf_all

array([[1.        , 0.96356801, 0.93884279, 0.85065114, 0.93933371,
        0.96231648, 0.87573433, 0.9205374 , 0.87611359, 0.94909636],
       [0.96356801, 1.        , 0.88291431, 0.82974706, 0.93079955,
        0.96383974, 0.95735362, 0.96887866, 0.91927189, 0.89723049],
       [0.93884279, 0.88291431, 1.        , 0.71160391, 0.86420616,
        0.89876268, 0.76080241, 0.87323837, 0.78572088, 0.95869425],
       [0.85065114, 0.82974706, 0.71160391, 1.        , 0.72245356,
        0.8468287 , 0.85195355, 0.84089233, 0.91267592, 0.69972935],
       [0.93933371, 0.93079955, 0.86420616, 0.72245356, 1.        ,
        0.89981174, 0.85432733, 0.83509733, 0.77484055, 0.93903142],
       [0.96231648, 0.96383974, 0.89876268, 0.8468287 , 0.89981174,
        1.        , 0.89637386, 0.92471757, 0.88413517, 0.89268554],
       [0.87573433, 0.95735362, 0.76080241, 0.85195355, 0.85432733,
        0.89637386, 1.        , 0.95856815, 0.96123774, 0.77563369],
       [0.9205374 , 0.96887866, 0.8732383